# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Costumer.create(name: 'Leonard Culham')
Costumer.create(name: 'Babette Juleff')
Costumer.create(name: 'Enrico Cubberley')
Costumer.create(name: 'Gusty Tuiller')
Costumer.create(name: 'Zachery Blinman')
Costumer.create(name: 'Pauly Boatright')
Costumer.create(name: 'Riannon Marriot')
Costumer.create(name: 'Staffard Todarini')
Costumer.create(name: 'Moss Ruf')
Costumer.create(name: 'Pat Burbage')
Costumer.create(name: 'Radcliffe Kingdon')
Costumer.create(name: 'Lindsy Joice')
Costumer.create(name: 'Barbabra Olyfat')
Costumer.create(name: 'Marcie MacGlory')
Costumer.create(name: 'Peder Dooly')
Costumer.create(name: 'Dionisio McKeowon')
Costumer.create(name: 'Perri Croy')
Costumer.create(name: 'Ring Dinnington')
Costumer.create(name: 'Renato Burnage')
Costumer.create(name: 'Franni Mc Gaughey')

Employee.create(name: 'Ronnica Belfit')
Employee.create(name: 'Alwyn Warden')
Employee.create(name: 'Meaghan Harvard')
Employee.create(name: 'Colas Danielovitch')
Employee.create(name: 'Camile Garling')
Employee.create(name: 'Rustie Corn')
Employee.create(name: 'Linnell Loude')
Employee.create(name: 'Marji Mordan')
Employee.create(name: 'Glennie Osbidston')
Employee.create(name: 'Darnall Fearby')
Employee.create(name: 'Bale Umpleby')
Employee.create(name: 'Isaiah Pocock')
Employee.create(name: 'Mallory Syers')
Employee.create(name: 'Quinton Olcot')
Employee.create(name: 'Xylina Iacivelli')
Employee.create(name: 'Wyndham Raffeorty')
Employee.create(name: 'Idaline Buckby')
Employee.create(name: 'Raeann Talboy')
Employee.create(name: 'Jorie Kesey')
Employee.create(name: 'Ondrea McOnie')

Product.create(name: 'Ginger - Fresh')
Product.create(name: 'Tart Shells - Sweet, 3')
Product.create(name: 'Meldea Green Tea Liquor')
Product.create(name: 'Nut - Chestnuts, Whole')
Product.create(name: 'Chocolate - Semi Sweet')
Product.create(name: 'Wine - Cava Aria Estate Brut')
Product.create(name: 'Madeira')
Product.create(name: 'Amarula Cream')
Product.create(name: 'Beans - Black Bean, Preserved')
Product.create(name: 'Cups 10oz Trans')
Product.create(name: 'Pike - Frozen Fillet')
Product.create(name: 'Plasticknivesblack')
Product.create(name: 'Bag - Bread, White, Plain')
Product.create(name: 'Wine - Magnotta - Belpaese')
Product.create(name: 'Wine - Red, Harrow Estates, Cab')
Product.create(name: 'Sage - Ground')
Product.create(name: 'Wine - Sawmill Creek Autumn')
Product.create(name: 'Tart Shells - Savory, 3')
Product.create(name: 'Berry Brulee')
Product.create(name: 'Soup - Tomato Mush. Florentine')

Property.create(name:'Fridge')
Property.create(name:'Microwave')
Property.create(name:'Ice-making machine')
Property.create(name:'Cash register')
Property.create(name:'Barcode scanner')
Property.create(name:'Computer monitor')
Property.create(name:'Counter')
Property.create(name:'Camera')
Property.create(name:'Scanner')
Property.create(name:'Freezer')



User.create(
  email: 'admin@gmail.com',
  password: '123456'
)
